version: '3'
services:
  payara-node1:
    image: payara-node
    container_name: payara-node1
    ports:
      - "10022:22"
      - "18080:28080"
      - "18081:28081"
  payara-node2:
    image: payara-node
    container_name: payara-node2
    ports:
      - "20022:22"
      - "28080:28080"
      - "28081:28081"
  payara-node3:
    image: payara-node
    container_name: payara-node3
    ports:
      - "30022:22"
      - "38080:28080"
      - "38081:28081"
  payara-das:
    build:
      context: .
      dockerfile:  payara-das.dockerfile
    container_name: payara-das
    ports:
      - "14848:4848"
    depends_on:
      - "payara-node1"
      - "payara-node2"
      - "payara-node3"
